-- Seed official Sanveda compliance PDFs for admin Documents module + public /documents page.

insert into public.documents (
  document_id,
  title,
  category,
  folder,
  description,
  owner,
  version,
  issue_date,
  expiry_date,
  visibility,
  status,
  tags,
  file_url,
  file_size_mb,
  downloads,
  views,
  shares,
  versions,
  is_compliance
)
values
  (
    'DOC-SVD-COI-001',
    'Certificate of Incorporation',
    'registration',
    'legal',
    'Certificate of Incorporation — Sanveda Global Humanitarian Foundation',
    'Compliance Team',
    'v1.0',
    '2026-07-10',
    null,
    'public',
    'published',
    '["coi","registration","incorporation","compliance"]'::jsonb,
    '/documents/coi-sanveda-global-humanitarian-foundation.pdf',
    0.46,
    0,
    0,
    0,
    '[{"version":"v1.0","author":"Admin","date":"2026-07-10","changeLog":"Official certificate uploaded","approvalStatus":"published"}]'::jsonb,
    true
  ),
  (
    'DOC-SVD-12A-001',
    '12A Registration Certificate',
    'tax',
    'compliance',
    'Section 12A registration certificate under the Income Tax Act, 1961',
    'Compliance Team',
    'v1.0',
    '2026-07-10',
    '2030-03-31',
    'public',
    'published',
    '["12a","tax","compliance"]'::jsonb,
    '/documents/12a-sanveda-global.pdf',
    1.53,
    0,
    0,
    0,
    '[{"version":"v1.0","author":"Admin","date":"2026-07-10","changeLog":"Official certificate uploaded","approvalStatus":"published"}]'::jsonb,
    true
  ),
  (
    'DOC-SVD-80G-001',
    '80G Registration Certificate',
    'certificate',
    'compliance',
    'Section 80G registration certificate under the Income Tax Act, 1961',
    'Compliance Team',
    'v1.0',
    '2026-07-10',
    '2028-03-31',
    'public',
    'published',
    '["80g","tax","compliance","donation"]'::jsonb,
    '/documents/80g-sanveda-global.pdf',
    1.11,
    0,
    0,
    0,
    '[{"version":"v1.0","author":"Admin","date":"2026-07-10","changeLog":"Official certificate uploaded","approvalStatus":"published"}]'::jsonb,
    true
  )
on conflict (document_id) do update set
  title = excluded.title,
  category = excluded.category,
  folder = excluded.folder,
  description = excluded.description,
  file_url = excluded.file_url,
  file_size_mb = excluded.file_size_mb,
  visibility = excluded.visibility,
  status = excluded.status,
  tags = excluded.tags,
  is_compliance = excluded.is_compliance,
  expiry_date = excluded.expiry_date,
  updated_at = now();
