import { BRAND } from './brand'

export const ASSETS = {
  logo: BRAND.logo,
  footerLogo: BRAND.logo,
  orangeSparks: '/assets/orange-sparks-2e0df875.svg',
  heart: '/assets/heart-30990fcb.svg',
  stringHand: '/assets/string-hand-bc11192c.svg',
  greenRope: '/assets/green-rope-79c4cf8c.svg',
  redOutlineHands: '/assets/red-outline-hands-88d1a4fc.svg',
  greenHand: '/assets/green-hand-d39b5820.svg',
  leftDoubleArrow: '/assets/left-double-arrow-d30210e1.svg',
  rightDoubleArrow: '/assets/right-double-arrow-ff7fdde3.svg',
  leftArrow: '/assets/left-arrow-eb45ec01.svg',
  bannerPattern: '/assets/sub-banner-pattern-816c10df.png',
  ourImpact: '/assets/OurImpact-e70006e2.png',
  backgroundStructure: '/assets/BackgroundStructure-24eee999.png',
  startCampaign: '/assets/StartNewCampaign-c03817e8.png',
  fallBackCard: '/assets/FallBackImageCard-043af4ab.png',
  fallBackBanner: '/assets/FallBackImageBanner-84c053c2.png',
  heroBanner: '/assets/hero-banner.jpg',
  donateMonthlyMask1: '/assets/DonateMonthlyMask1-e0aac12d.svg',
  donateMonthlyMask2: '/assets/DonateMonthlyMask2-d832d673.svg',
  donateMonthlyMask3: '/assets/DonateMonthlyMask3-5c9bc9d4.svg',
  pinkSplash: '/assets/pink-splash-5f5b42c4.svg',
  pinkCircles: '/assets/pink-circles-1f83ce95.svg',
  heroMask1: '/assets/HeroSectionMask1-afb43fb8.svg',
  heroMask2: '/assets/HeroSectionMask2-1a7d2309.svg',
  heroMask3: '/assets/HeroSectionMask3-d706fafc.svg',
  quote: '/assets/quote-61078550.svg',
  rupee: '/assets/rupee-4f3f93dd.svg',
  greenLightning: '/assets/GreenLightning-9fe62515.svg',
  mastercard: '/assets/mastercard-logo-1a0d63c0.svg',
  visa: '/assets/visa-logo-2118261f.svg',
  upi: '/assets/upi-logo-78ee8a18.svg',
  arrowUpRight: '/assets/arrow-up-right-56a1da88.svg',
  maskRedBox: '/assets/MaskRedBox-d6f428e9.svg',
  monthlyMaskDesign: '/assets/MonthlyMaskDesign-7e256edd.svg',
  tick: '/assets/tick-8350a606.svg',
  whiteHeart: '/assets/white-heart-75c4f211.svg',
  pinkHearts: '/assets/pink-hearts-5b85906d.svg',
  whatsapp: '/assets/whatsapp-30a5e326.svg',
  tap: '/assets/tap-216bf6bc.svg',
  creditCard: '/assets/credit-card-5756e35d.svg',
  greenRupee: '/assets/green-rupee-2dd141fc.svg',
  notification: '/assets/notification-968f6e2d.svg',
  people: '/assets/people-aeb949fe.svg',
  wcuClock: '/assets/WCUclock-a17aec63.svg',
  wcuHeart: '/assets/WCUheart-19eace43.svg',
  wcuCalendar: '/assets/WCUcalendar-f451f44b.svg',
  wcuMoney: '/assets/WCUmoney-7eb2ff57.svg',
  wcuHappyEmoji: '/assets/WCUhappyemoji-c2becd52.svg',
  wcuVerify: '/assets/WCUverify-0bf4baba.svg',
  starIcon: '/assets/streamline-sharp_star-2a3e8dd9.svg',
  dropdownArrow: '/assets/dropdown-arrow-7df8388c.svg',
  footerFacebook: '/assets/footer-facebook-1cfb065b.svg',
  footerLinkedin: '/assets/footer-linkedin-288e40ce.svg',
  footerInstagram: '/assets/footer-instagram-3e4c1f0c.svg',
  footerTwitter: '/assets/footer-twitter-84cc274f.svg',
  americanExpress: '/assets/american-express-logo-56a1da88.svg',
  yellowHearts: '/assets/yellow-hearts-ce710a3b.svg',
  whiteHearts: '/assets/white-hearts-13fac52f.svg',
} as const

export const WCU_ICONS = [
  ASSETS.wcuClock,
  ASSETS.wcuHeart,
  ASSETS.wcuCalendar,
  ASSETS.wcuMoney,
  ASSETS.wcuHappyEmoji,
  ASSETS.wcuVerify,
] as const

export const MONTHLY_STEP_ICONS = [
  ASSETS.tap,
  ASSETS.creditCard,
  ASSETS.greenRupee,
  ASSETS.notification,
] as const
